name: fetch_firmwares

on: [push]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: robinraju/release-downloader@v1.8
        with: 
          # The source repository path.
          # Expected format {owner}/{repo}
          # Default: ${{ github.repository }}
          repository: "steadramon/ESPGeiger"
          
          # A flag to set the download target as latest release
          # The default value is 'false'
          latest: true
          
          # The name of the file to download.
          # Use this field only to specify filenames other than tarball or zipball, if any.
          # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
          fileName: "*.bin"
          
          # Download the attached tarball (*.tar.gz)
          tarBall: false
          
          # Download the attached zipball (*.zip)
          zipBall: false
          
          # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
          # It will create the target directory automatically if not present
          # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
          out-file-path: "downloaded"
    commitgit:
      needs: download
      - name: Push updated master firmwares in branch firmware
        run: |
          COMMIT="Firmware built from ${{steps.download.outputs.tag_name}}"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git commit --allow-empty -m "$COMMIT"
          git push origin firmware -f