name: fetch_firmwares

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths:
      - 'trigger_devel.txt'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: release.yml
          repo: steadramon/ESPGeiger
          name: *firmware.bin
          name_is_regexp: true
